services:
  - type: web
    name: quran-tracker
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn quran_tracker.wsgi:application --timeout 120 --workers 2 --preload
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: DATABASE_URL
        fromDatabase:
          name: quran-tracker-db
          property: connectionString
      - key: BOOTSTRAP_ADMIN_USERNAME
        value: khalid1
      - key: BOOTSTRAP_ADMIN_PASSWORD
        sync: false
      - key: BOOTSTRAP_TEACHER_USERNAME
        value: teacher
      - key: BOOTSTRAP_TEACHER_PASSWORD
        sync: false
    autoDeploy: true

databases:
  - name: quran-tracker-db
    plan: free
    databaseName: quran_tracker
    user: quran_tracker
