# Generated by Django 6.0.7 on 2026-07-20 22:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reading_type', models.CharField(choices=[('memorization', 'Memorization'), ('quran_reading', 'Quran Reading'), ('qaida_book', 'Qaida/Book Reading')], max_length=20)),
                ('minutes_read', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount_read', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('pages', 'Pages'), ('ayahs', 'Ayahs')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_daily_log_per_student')],
            },
        ),
    ]
