# Generated by Django 6.0.7 on 2026-07-21 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_approved',
            field=models.BooleanField(default=False, help_text='Only admin can approve teacher accounts.'),
        ),
    ]
